import type { CustomerPage } from '../types/customerPage'

const now = new Date()
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000).toISOString()
const daysAhead = (days: number) => new Date(now.getTime() + days * 86400000).toISOString()

export const samplePages: CustomerPage[] = [
  {
    id: 'pg_001',
    slug: 'luna-birthday-joy',
    recipientName: 'Luna Rahman',
    senderName: 'Arif',
    occasion: 'Birthday',
    packageType: 'premium',
    title: 'A Garden of Love for You',
    subtitle: 'Happy birthday, Luna',
    shortMessage: 'Every flower in this bouquet carries a thank you for being you.',
    longLetter:
      'To my dearest Luna,\\n\\nOn your birthday, I wanted to give you something that feels as warm and soft as your presence. Thank you for your kindness, your laughter, and your unwavering heart. I hope this bouquet is a reminder that you are deeply loved.\\n\\nAlways yours,\\nArif',
    videoUrl: 'https://www.youtube.com/embed/1La4QzGeaaQ',
    gallery: [
      'https://images.unsplash.com/photo-1455659817273-f96807779a8a?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=900&q=80',
    ],
    musicUrl: '',
    status: 'active',
    unlockAt: null,
    views: 126,
    lastViewedAt: daysAgo(0),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
    themePreset: 'rose',
    passwordEnabled: false,
    giftAccessPassword: '',
    timedUnlockEnabled: false,
    notifyOnOpen: true,
    musicAutoplay: false,
    themeAccentColor: '',
    themeBackgroundImageUrl: '',
    occasionIcon: 'cake',
    selectedCardTemplate: 'classic-romantic',
    cardHeadline: '',
    cardSubtext: '',
    cardRecipientName: '',
  },
  {
    id: 'pg_002',
    slug: 'nabila-anniversary',
    recipientName: 'Nabila Chowdhury',
    senderName: 'Sami',
    occasion: 'Anniversary',
    packageType: 'standard',
    title: 'For Our Beautiful Journey',
    subtitle: 'Another year, another chapter',
    shortMessage: 'Thank you for choosing me every single day.',
    longLetter: '',
    videoUrl: 'https://www.youtube.com/embed/00k2f7V5N4U',
    gallery: [],
    musicUrl: '',
    status: 'active',
    unlockAt: null,
    views: 78,
    lastViewedAt: daysAgo(2),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(3),
    themePreset: 'classic',
    passwordEnabled: false,
    giftAccessPassword: '',
    timedUnlockEnabled: false,
    notifyOnOpen: true,
    musicAutoplay: false,
    themeAccentColor: '',
    themeBackgroundImageUrl: '',
    occasionIcon: 'ring',
    selectedCardTemplate: 'classic-romantic',
    cardHeadline: '',
    cardSubtext: '',
    cardRecipientName: '',
  },
  {
    id: 'pg_003',
    slug: 'zara-graduation',
    recipientName: 'Zara Hasan',
    senderName: 'Family',
    occasion: 'Graduation',
    packageType: 'basic',
    title: 'We are proud of you',
    subtitle: 'Class of 2026',
    shortMessage: 'Your hard work bloomed beautifully. Congratulations!',
    longLetter: '',
    videoUrl: '',
    gallery: [],
    musicUrl: '',
    status: 'draft',
    unlockAt: daysAhead(3),
    views: 0,
    lastViewedAt: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    themePreset: 'warm-minimal',
    passwordEnabled: false,
    giftAccessPassword: '',
    timedUnlockEnabled: true,
    notifyOnOpen: true,
    musicAutoplay: false,
    themeAccentColor: '',
    themeBackgroundImageUrl: '',
    occasionIcon: 'heart',
    selectedCardTemplate: 'graduation',
    cardHeadline: '',
    cardSubtext: '',
    cardRecipientName: '',
  },
  {
    id: 'pg_004',
    slug: 'sara-thankyou',
    recipientName: 'Sara Ahmed',
    senderName: 'Team Himaya',
    occasion: 'Thank You',
    packageType: 'premium',
    title: 'A small token of gratitude',
    subtitle: 'With love from all of us',
    shortMessage: 'Your support helped us bloom this year.',
    longLetter: 'Sara, your trust means everything to our team. Thank you for being with us.',
    videoUrl: '',
    gallery: [
      'https://images.unsplash.com/photo-1487073240288-854ac7f1bb3c?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=900&q=80',
    ],
    musicUrl: '',
    status: 'archived',
    unlockAt: null,
    views: 41,
    lastViewedAt: daysAgo(9),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(45),
    themePreset: 'classic',
    passwordEnabled: false,
    giftAccessPassword: '',
    timedUnlockEnabled: false,
    notifyOnOpen: false,
    musicAutoplay: false,
    themeAccentColor: '',
    themeBackgroundImageUrl: '',
    occasionIcon: 'flower',
    selectedCardTemplate: 'minimal-premium',
    cardHeadline: '',
    cardSubtext: '',
    cardRecipientName: '',
  },
]
